### PR TITLE
[WIP] Allow a context parameter that is threaded through all parse calls

### PR DESCRIPTION
**Pull request by kevinmehall**
Implementation of #84

### CODE REVIEW

**Comment by ebfull** [comment]
I [submitted a PR](https://github.com/kevinmehall/rust-peg/pull/103) to your `context` branch which adds an additional `#[static]` attribute for static parse rules. This can serve as an alternative for users who don't need to thread a context object from the outside into the grammar, and where the grammar would benefit (readability wise) when it depends on context that is entirely local to the grammar.

**Comment by ebfull** [comment]
There's a potentially better design for this, but it might require more work.

```rust
#[pub(something: usize)]
parse
    = foo { println!("{}", something); }
    / bar

...
```

This would require us to write `parse_` variants for every unique context argument list that reaches a given rule from the dependency graph of rules. The upside is that `#![context(T)]` is avoided (which is ugly IMHO) and we don't need to impose a context object on all rules even when those rules do not need it.

**Comment by jonas-schievink** [comment]
Hey @kevinmehall, what's the status of this?

**Comment by kevinmehall** [comment]
I haven't had much time to work on rust-peg lately, but I hope to get to it soon. I do want to explore some of the design alternatives since I agree with @ebfull that this is a little ugly.

**Pull request closed without merging**
