### PR TITLE
Add nested elements PEG example

### PR DESCRIPTION
**Pull request by bartolsthoorn**
This example shows how to parse nested elements using `enum`. It's basically a very simple XML/HTML parser. The existing examples don't really show how to do this.

### CODE REVIEW

**Comment by untitaker** [comment]
Hmm @kevinmehall this has been hanging around for pretty long now...

**Comment by kevinmehall** [comment]
Yeah... sorry about that!

Would S-expressions be a better example than a small subset of XML? Since this one doesn't check the contents of the end tag, and doesn't handle attributes, it's closer to S-expressions anyway.

Ideally it would be small enough to include inline in the readme, but that might not be possible without oversimplifying important things like whitespace rules.

**Comment by bartolsthoorn** [comment]
I understand what you mean, but this example does not aim to be a full XML parser anyway. I just added this because I think it shows some of the more advanced stuff you can do with rust-peg. The other examples are very good and clear, but quite basic.

**Comment by ivanceras** [comment]
@bartolsthoorn What library are you using for the html element on these example? I looked at your fork repo but couldn't figure out either.

**Comment by bartolsthoorn** [comment]
@ivanceras I'm sorry but I don't understand your question. In this file I just show how to set up a very basic XML/HTML parser using only rust-peg, and in `fn main()` I test it on `<div><em>ABC</em></div>" `. Only rust-peg is used, because PEG can be used to parse nested elements.

**Comment by ivanceras** [comment]
@bartolsthoorn I was trying to run your examples, but there has been errors.
It seems like super is not working in recent version of rust.

```rust
#![feature(plugin)]
#![plugin(peg_syntax_ext)]

use parser::element;

enum Node {
  Text(String),
  Element(String, Vec<Node>)
}

peg! parser(r#"
#[pub]
element -> super::Node
  = s:start_tag c:content e:end_tag { super::Element(s, c) }
name -> String
  = [a-zA-Z0-9_]+ { match_str.to_string() }
start_tag -> String
  = "<" n:name ">" { n }
end_tag -> String
  = "</" n:name ">" { n }
content -> Vec<super::Node>
  = (element / text)*
text -> super::Node
  = (!start_tag !end_tag .)+ { super::Text(match_str.to_string()) }
"#);

fn main() {
  let result = element("<div><em>ABC</em></div>");
  assert!(result.is_ok());

  let node = result.unwrap();
  assert_eq!(
    match node {
      Text(_) => unimplemented!(),
      Element(name, _) => name
    }, "div".to_string());

  let child = match node {
    Element(_, ref children) => children.index(&0),
    _ => unimplemented!()
  };

  let text = match *child {
    Element(_, ref children) => children.index(&0),
    _ => unimplemented!()
  };

  assert_eq!(
    match *text {
      Text(ref t) => t.clone(),
      _ => unimplemented!()
    }, "ABC".to_string());
}
```

```sh
:1:3: 1:17 error: unresolved name `super::Element` [E0425]
:1 { super::Element(s, c) }
     ^~~~~~~~~~~~~~
test_xml.rs:11:1: 25:5 note: in this expansion of peg! (defined in test_xml.rs)
:1:3: 1:17 help: run `rustc --explain E0425` to see a detailed explanation
:1:3: 1:14 error: unresolved name `super::Text` [E0425]
:1 { super::Text(match_str.to_string()) }
     ^~~~~~~~~~~
test_xml.rs:11:1: 25:5 note: in this expansion of peg! (defined in test_xml.rs)
:1:3: 1:14 help: run `rustc --explain E0425` to see a detailed explanation
test_xml.rs:34:7: 34:11 error: unresolved enum var
```

I like your examples because it returns the parts of matched expressions. 
Most examples in rust-peg are mostly just returns Ok or Err as evaluation result.

https://github.com/kevinmehall/rust-peg/issues/114

I always thought parsers return which parts of the expression match like regex, and can later be used to programmatically process it further.

**Comment by ivanceras** [comment]
This little project I've just build can helpful for those who are looking for example usage.
https://github.com/ivanceras/inquerest

**Comment by kevinmehall** [comment]
Sorry for not getting this merged 5 years ago! We have some better docs now.

**Pull request closed without merging**
